// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define PIN_CLK 13

// ------- //
// uart_tx //
// ------- //

#define uart_tx_wrap_target 0
#define uart_tx_wrap 9

static const uint16_t uart_tx_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1     
    0x200d, //  1: wait   0 gpio, 13                 
    0x208d, //  2: wait   1 gpio, 13                 
    0xf028, //  3: set    x, 8            side 0     
    0x200d, //  4: wait   0 gpio, 13                 
    0x208d, //  5: wait   1 gpio, 13                 
    0x6001, //  6: out    pins, 1                    
    0x0044, //  7: jmp    x--, 4                     
    0x200d, //  8: wait   0 gpio, 13                 
    0x208d, //  9: wait   1 gpio, 13                 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_tx_program = {
    .instructions = uart_tx_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config uart_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_tx_wrap_target, offset + uart_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ------- //
// uart_rx //
// ------- //

#define uart_rx_wrap_target 0
#define uart_rx_wrap 9

static const uint16_t uart_rx_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0                   
    0xe028, //  1: set    x, 8                       
    0x208d, //  2: wait   1 gpio, 13                 
    0x200d, //  3: wait   0 gpio, 13                 
    0x00c0, //  4: jmp    pin, 0                     
    0x208d, //  5: wait   1 gpio, 13                 
    0x200d, //  6: wait   0 gpio, 13                 
    0x4001, //  7: in     pins, 1                    
    0x0045, //  8: jmp    x--, 5                     
    0x8020, //  9: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_rx_program = {
    .instructions = uart_rx_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config uart_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_rx_wrap_target, offset + uart_rx_wrap);
    return c;
}

#include "hardware/clocks.h"
#define  SM_TX   1
#define  SM_RX   2
static inline void pio_uart_init(PIO pio, uint rx_offset, uint tx_offset, uint pin_rx, uint pin_tx, uint freq)
{
	float clock_divider = (float) clock_get_hz(clk_sys) / freq;
	gpio_pull_up(PIN_CLK);
	gpio_pull_up(pin_rx);
	pio_gpio_init(pio, pin_rx);
	pio_gpio_init(pio, pin_tx);
	//configure RX SM
	pio_sm_set_consecutive_pindirs(pio, SM_RX, pin_rx, 1, false);
	pio_sm_config rx = uart_rx_program_get_default_config(rx_offset);
	sm_config_set_in_shift(&rx, true, false, 9);
	sm_config_set_in_pins(&rx, pin_rx);
	sm_config_set_jmp_pin(&rx, pin_rx);
	sm_config_set_fifo_join(&rx, PIO_FIFO_JOIN_NONE);
	sm_config_set_clkdiv(&rx, clock_divider);
	pio_sm_init(pio, SM_RX, rx_offset, &rx);
	pio_sm_set_enabled(pio, SM_RX, true);
	//configure TX SM
	pio_sm_set_pins_with_mask(pio, SM_TX, 1u << pin_tx, 1u << pin_tx);
	pio_sm_set_consecutive_pindirs(pio, SM_TX, pin_tx, 1, true);
	pio_sm_config tx = uart_tx_program_get_default_config(tx_offset);
	sm_config_set_out_shift(&tx, true, false, 9);
	sm_config_set_out_pins(&tx, pin_tx, 1);
	sm_config_set_sideset_pins(&tx, pin_tx);
	sm_config_set_fifo_join(&tx, PIO_FIFO_JOIN_NONE);
	sm_config_set_clkdiv(&tx, clock_divider);
	pio_sm_init(pio, SM_TX, tx_offset, &tx);
	pio_sm_set_enabled(pio, SM_TX, true);
}
static inline bool uart_rx_program_getc(PIO pio, uint sm, char *c) {
	uint32_t value = pio_sm_get_blocking(pio, sm);
	uint8_t parity = (value >> 31);
	*c = (value >> 23) & 0xFF;
	for (int i = 0; i < 8; ++i) {
		parity += (*c >> i) & 0x01;
	}
	return !(parity % 2);
}
static inline void uart_tx_program_putc(PIO pio, uint sm, char c) {
	uint32_t value = (uint32_t)c;
	uint8_t parity = 0;
	for (int i = 0; i < 8; ++i) {
		parity += (c >> i) & 0x01;
	}
	value = value | ((parity % 2) << 8);
	pio_sm_put_blocking(pio, sm, value);
}

#endif

